# Generated by Django 4.2.23 on 2025-08-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgrecord',
            name='file_type',
            field=models.CharField(default='csv', max_length=10),
        ),
    ]
