# Generated by Django 4.2.23 on 2026-02-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecgapp', '0002_ecgrecord_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecgrecord',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecgrecord',
            name='heart_image',
            field=models.ImageField(blank=True, null=True, upload_to='heart_views/'),
        ),
        migrations.AlterField(
            model_name='ecgrecord',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('csv', 'CSV')], default='image', max_length=10),
        ),
    ]
